project:
  type: website
  output-dir: docs

website:
  title: "Geekyrakshit"
  twitter-card: true
  favicon: assets/soumik_rakshit.png
  site-url: https://geekyrakshit.dev
  open-graph: true
  navbar:
    right:
      - about.qmd
      - courses.qmd
      - wandb_reports.qmd
      - posts.qmd
format:
  html:
    theme:
      light: simplex
      dark: darkly
    css: styles.css
