project:
  type: website
  output-dir: docs

website:
  title: "Geekyrakshit"
  twitter-card: true
  favicon: assets/soumik_rakshit.png
  site-url: https://geekyrakshit.dev
  open-graph: true
  navbar:
    right:
      - about.qmd
      - wandb_reports.qmd
      - posts.qmd
      - icon: github
        href: https://github.com/soumik12345
      - icon: twitter
        href: https://twitter.com/soumikRakshit96
      - icon: linkedin
        href: https://linkedin.com/in/soumikrakshit/
      - text: "{{< fa brands kaggle >}} "
        href: https://www.kaggle.com/soumikrakshit
      - icon: steam
        href: https://steamcommunity.com/id/geekyRakshit/
format:
  html:
    theme:
      light: simplex
      dark: darkly
    css: styles.css
